/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.35
 * Generated at: 2016-04-12 08:29:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import java.util.*;

public final class distanceshow_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {


    Connection con=null;
    Statement st=null;
    ResultSet rs=null;
    String driver="com.mysql.jdbc.Driver";
    String url="jdbc:mysql://localhost:3306/meetingsheduler";
	Vector finalResults=new Vector();

    

    
  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("  \r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<title>My Cloud Space</title>\r\n");
      out.write("<meta name=\"keywords\" content=\"free css, web template, cloudy\" />\r\n");
      out.write("<meta name=\"description\" content=\"Cloudy - free website template provided by templatemo.com\" />\r\n");
      out.write("<link href=\"templatemo_style.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/featuredcontentglider.css\" />\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"nivo-slider.css\" type=\"text/css\" media=\"screen\" />\r\n");
      out.write("\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\">\r\n");
      out.write("function clearText(field)\r\n");
      out.write("{\r\n");
      out.write("    if (field.defaultValue == field.value) field.value = '';\r\n");
      out.write("    else if (field.value == '') field.value = field.defaultValue;\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"css/featuredcontentglider.js\"></script>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title></title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div id=\"templatemo_wrapper_outer\">\r\n");
      out.write("<div id=\"templatemo_wrapper\">\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"temmplatmeo_header\">\r\n");
      out.write("    \r\n");
      out.write("   \t\t<div id=\"site_title\">\r\n");
      out.write("           \t<a href=\"#\">\r\n");
      out.write("            \t\r\n");
      out.write("            \t<span>My Cloud Space</span>\r\n");
      out.write("            </a>\r\n");
      out.write("        </div>\r\n");
      out.write("    \r\n");
      out.write("    \t<div id=\"templatemo_menu\">\r\n");
      out.write("        \r\n");
      out.write("            <ul>\r\n");
      out.write("                <li><a href=\"#\" class=\"current\">Home</a></li>\r\n");
      out.write("                <li><a href=\"about.html\">About Us</a></li>\r\n");
      out.write("                <li><a href=\"service.html\">Services</a></li>\r\n");
      out.write("          \t\t<li><a href=\"contact.html\">Contact </a></li>\r\n");
      out.write("            </ul>    \t\r\n");
      out.write("        \r\n");
      out.write("        </div> <!-- end of templatemo_menu -->\r\n");
      out.write("    \r\n");
      out.write("    </div> <!-- end of templatemo_header -->\r\n");
      out.write("    \r\n");
      out.write("    <div id=\"templatemo_content_wrapper_top\"></div>\r\n");
      out.write("    <div id=\"templatemo_content_wrapper\">\r\n");
      out.write("    \r\n");
      out.write("    \t\r\n");
      out.write("    \r\n");
      out.write("        <div id=\"templatemo_banner\"><span class=\"frame\"></span>\r\n");
      out.write("        \r\n");
      out.write("\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("    \r\n");
      out.write("            featuredcontentglider.init({\r\n");
      out.write("                gliderid: \"canadaprovinces\", //ID of main glider container\r\n");
      out.write("                contentclass: \"glidecontent\", //Shared CSS class name of each glider content\r\n");
      out.write("                togglerid: \"p-select\", //ID of toggler container\r\n");
      out.write("                remotecontent: \"\", //Get gliding contents from external file on server? \"filename\" or \"\" to disable\r\n");
      out.write("                selected: 0, //Default selected content index (0=1st)\r\n");
      out.write("                persiststate: false, //Remember last content shown within browser session (true/false)?\r\n");
      out.write("                speed: 500, //Glide animation duration (in milliseconds)\r\n");
      out.write("                direction: \"rightleft\", //set direction of glide: \"updown\", \"downup\", \"leftright\", or \"rightleft\"\r\n");
      out.write("                autorotate: true, //Auto rotate contents (true/false)?\r\n");
      out.write("                autorotateconfig: [3000, 2] //if auto rotate enabled, set [milliseconds_btw_rotations, cycles_before_stopping]\r\n");
      out.write("            })\r\n");
      out.write("            \r\n");
      out.write("            </script>\r\n");
      out.write("            \r\n");
      out.write("            <div id=\"canadaprovinces\" class=\"glidecontentwrapper\">\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"glidecontent\">\r\n");
      out.write("                <img src=\"images/temp3.png\" alt=\"bird\" />\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"glidecontent\">\r\n");
      out.write("            <img src=\"images/temp2.jpg\" alt=\"image\" />\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"glidecontent\">\r\n");
      out.write("            <img src=\"images/TEMP1.jpg\" alt=\"image\" />\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <div id=\"p-select\" class=\"cssbuttonstoggler\">\r\n");
      out.write("            <a href=\"#\" class=\"toc\"><span>1</span></a> <a href=\"#\" class=\"toc\"><span>2</span></a> <a href=\"#\" class=\"toc\"><span>3</span></a>\r\n");
      out.write("            \r\n");
      out.write("            </div>\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        </div> <!-- end of templatemo_banner -->\r\n");
      out.write("    \t    \r\n");
      out.write("    \r\n");
      out.write("    \t<div id=\"content\">\r\n");
      out.write("        \r\n");
      out.write("        \t<div class=\"full_width\" style=\"background-color:#C2D6FF; border:2px solid #6699FF;\">\r\n");
      out.write("        \t\r\n");
      out.write("        \t\r\n");
      out.write("           <center>\r\n");
      out.write("           ");

if(session.getAttribute("meetingplace")!=null){
	Vector names=new Vector();
	Vector results=new Vector();
	String commonLat="";
	String commonLong="";
	

String meetingPlace=(String)session.getAttribute("meetingplace");


Class.forName(driver);
con=DriverManager.getConnection(url,"root","root");
st=con.createStatement();
rs=st.executeQuery("Select * from selectedusers");
while(rs.next()){
	names.add(rs.getString(1));
	}
for(int val=0;val<names.size();val++){
	rs=st.executeQuery("select *from userinformation where staffname='"+names.get(val).toString()+"'");
	while(rs.next()){
		results.add(rs.getString(2));
		results.add(rs.getString(12));
		results.add(rs.getString(13));
		results.add(rs.getString(14));
		results.add(rs.getString(15));
	}}
	rs=st.executeQuery("select * from mapdetails where hotel='"+meetingPlace+"'");

	if(rs.next()){
		commonLat=rs.getString(2);
		

	commonLong=rs.getString(3);
	}
	finalResults=new Vector();
	for(int commons=0;commons<results.size();commons=commons+5){
		 
		 double theta=Double.parseDouble(results.get(commons+3).toString()) -Double.parseDouble(commonLong);
		double dist =Math.sin(Double.parseDouble(results.get(commons+2).toString()) * Math.PI/180.0) *Math.sin(Double.parseDouble(commonLat) * Math.PI / 180.0) + Math.cos(Double.parseDouble(results.get(commons+2).toString()) * Math.PI / 180.0) * Math.cos(Double.parseDouble(commonLat)* Math.PI / 180.0) * Math.cos(theta * Math.PI / 180.0);
		 dist = Math.acos(dist);
		 dist = dist * 180.0 /Math.PI;
		dist = dist * 60 * 1.1515;
		 dist = dist * 1.609344;
		 

	finalResults.add(results.get(commons).toString());
	finalResults.add(results.get(commons+1).toString());
	finalResults.add(meetingPlace);
	finalResults.add(String.valueOf(dist).substring(0,4));
	}}

      out.write("\r\n");
      out.write("<table border=\"1\" cellpadding=\"8\" cellspacing=\"8\" style=\"overflow: scroll;height: auto;\">\r\n");
      out.write("        \t<th bgcolor=\"\" colspan=\"5\"><font size=\"5\" color=\"red\"><center>Staff Information</center></font></th>\r\n");
      out.write("        \t<tr><td><b>Staff Name</b></td><td><b>Current Location</b></td><td><b>Meeting Place</b></td><td><b>Distance<br>( appx in Km)</b></td></tr>\r\n");
      out.write("        \t");

        	for(int val=0;val<finalResults.size();val=val+4){
        		
      out.write("\r\n");
      out.write("        \t\t<tr>\r\n");
      out.write("        \t\t<td>");
      out.print(finalResults.get(val).toString() );
      out.write("</td>\r\n");
      out.write("        \t\t<td>");
      out.print(finalResults.get(val+1).toString() );
      out.write("</td>\r\n");
      out.write("        \t\t<td>");
      out.print(finalResults.get(val+2).toString() );
      out.write("</td>\r\n");
      out.write("        \t\t<td>");
      out.print(finalResults.get(val+3).toString() );
      out.write("</td>\r\n");
      out.write("        \t\t</tr>\r\n");
      out.write("        \t");

        	}
        	
      out.write("\r\n");
      out.write("        \t\r\n");
      out.write("        \t\t</table><br>\r\n");
      out.write("        \t\t<input type=\"submit\" value=\"Back To Staff Selection\" style=\"margin:0 0 0 120px;border: 2;background-color: maroon;font-family: serif;color: white;\" onclick=\"window.location.href='selectuser.jsp'\"><br><br>\r\n");
      out.write("        \r\n");
      out.write("           </center>\r\n");
      out.write("        \r\n");
      out.write("\t\t</div> <!-- end of content -->\r\n");
      out.write("        </div>\r\n");
      out.write("</div><div id=\"templatemo_content_wrapper_bottom\"></div> <!-- end of templatemo_wrapper -->\r\n");
      out.write("\r\n");
      out.write("        <div id=\"templatemo_footer\"> </div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
