/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.35
 * Generated at: 2016-05-09 07:57:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import java.util.*;
import javax.mail.internet.*;
import javax.mail.Session;
import com.sun.*;
import java.net.*;
import javax.mail.Transport;
import javax.mail.Message.*;

public final class mail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {


    Connection con=null;
    Statement st=null;
    ResultSet rs=null;
    String driver="com.mysql.jdbc.Driver";
    String url="jdbc:mysql://localhost:3306/meetingsheduler";
    ArrayList selectdUsers=new ArrayList();
    ArrayList userdetails=new ArrayList();


    
  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("     \r\n");
      out.write("     \r\n");
      out.write("     \r\n");
      out.write("     ");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");

if((request.getParameter("date")!=null)&&(request.getParameter("title")!=null) &&(request.getParameter("org")!=null)&&(request.getParameter("time")!=null)&&(request.getParameter("venue")!=null)){
String date=request.getParameter("date");
String title=request.getParameter("title");
String org=request.getParameter("org");
String time=request.getParameter("time");
String venue=request.getParameter("venue");

String host = "smtp.gmail.com";
String userid = "krishreddy56@gmail.com"; 
String password = "9490904777";
String subject=" Regarding Meeting";
Class.forName(driver);
con=DriverManager.getConnection(url,"root","root");
st=con.createStatement();
rs=st.executeQuery("select * from mapdetails where hotel='"+venue+"'");
if(rs.next()){
	String venues=rs.getString(5);
	venue=venue + ";" +venues.replaceAll(",",";");
}
rs=st.executeQuery("select * from selectedusers");
selectdUsers=new ArrayList();
while(rs.next()){
	selectdUsers.add(rs.getString(1));
	selectdUsers.add(rs.getString(5));
	
}
if(selectdUsers.size()>0){
	userdetails=new ArrayList();
	
	for(int val=0;val<selectdUsers.size();val=val+2){
		rs=st.executeQuery("select * from userinformation where mobilenumber='"+selectdUsers.get(val+1).toString()+"'");
		if(rs.next()){
			userdetails.add(rs.getString(2));
			userdetails.add(rs.getString(7));
			userdetails.add(rs.getString(8));
			
		}

		
	}
	System.out.println("the selected users are"+userdetails);
	if(userdetails.size()>0){
		for(int init=0;init<userdetails.size();init=init+3){
			try
			{
				System.out.println(userdetails.size());
			Properties props = System.getProperties(); 
			props.put("mail.smtp.starttls.enable", "true"); 
			props.put("mail.smtp.host", host); 
			props.setProperty("mail.transport.protocol", "smtps");
			props.put("mail.smtp.user", userid); 
			props.put("mail.smtp.password", password); 
			props.put("mail.smtp.port", "465"); 
			props.put("mail.smtps.auth", "true"); 
			Session session1 = Session.getDefaultInstance(props, null); 
			MimeMessage message = new MimeMessage(session1); 
			InternetAddress fromAddress = null;
			InternetAddress toAddress = null;
			
			fromAddress = new InternetAddress(userid);

			for(int count=1;count<3;count++){
			try {
				System.out.println(count+"i"+init+userdetails.get(count+init).toString());
			
			toAddress = new InternetAddress(userdetails.get(count+init).toString());
			
			message.setFrom(fromAddress);
			message.setRecipient(RecipientType.TO, toAddress);
			message.setSubject(subject);
		    
			message.setText("Hai "+userdetails.get(init).toString()+","+"\n"+"Your Meeting Title is :"+title+"\n"+"Your Meeting Organizer :"+org+"\n"+"Your Meeting Time is :"+time+"\n"+"Your Meeting Venue is :"+venue); 
			

			Transport transport = session1.getTransport("smtps"); 
			transport.connect(host, userid, password); 
			transport.sendMessage(message, message.getAllRecipients()); 
			
			transport.close(); 
			} catch (Exception e) {
				//out.print("Error...");
			e.printStackTrace();
			
			
			}
			
			} }catch (Exception e) {
		//	e.printStackTrace();
			}
		}
		out.print("Successfully Send to Mail...");
		System.out.println("Completed");
		}
	Vector finalVals=new Vector();
	for(int vals=0;vals<selectdUsers.size();vals=vals+2){
		System.out.println("the user mobnum"+selectdUsers.get(vals+1).toString().trim());
		rs=st.executeQuery("select * from userinformation where mobilenumber='"+selectdUsers.get(vals+1).toString().trim()+"'");
		if(rs.next()){
			finalVals.add(rs.getString(10));
			finalVals.add(selectdUsers.get(vals+1).toString());
			finalVals.add(date);
			finalVals.add(title);
			finalVals.add(org);
			finalVals.add(rs.getString(12));
			finalVals.add(venue);
		}
		
		
		
		
		
		
	}
	
    System.out.println("the final values are"+finalVals);
    //st.executeUpdate("")
	if(finalVals.size()>0){
		for(int init=0;init<finalVals.size();init=init+7){
			int insert=st.executeUpdate("insert into meetinginfo values('"+finalVals.get(init).toString()+"','"+finalVals.get(init+1).toString()+"','"+finalVals.get(init+2).toString()+"','"+finalVals.get(init+3).toString()+"','"+finalVals.get(init+4).toString()+"','"+finalVals.get(init+5).toString()+"','"+finalVals.get(6).toString()+"')");
			
		}
	}
		
	}

}

      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
