/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.35
 * Generated at: 2016-04-12 08:26:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import java.util.*;
import java.io.*;
import java.net.*;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.json.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {


    Connection con=null;
    Statement st=null;
    ResultSet rs=null;
    BufferedReader in=null;
    StringBuffer sb=new StringBuffer("");

    String driver="com.mysql.jdbc.Driver";
    String url="jdbc:mysql://localhost:3306/meetingsheduler";
    
    
  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title></title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");

if((request.getParameter("staffname")!=null)&&(request.getParameter("mobile")!=null)){
	String name=request.getParameter("staffname");
	String dob=request.getParameter("dob");
	String proj=request.getParameter("proj");
	String loc=request.getParameter("loc");
	String dsgn=request.getParameter("dsgn");
	String mail=request.getParameter("mail");
	String pmail=request.getParameter("pmail");
	String mobile=request.getParameter("mobile");
	String user=request.getParameter("user");
	String pass=request.getParameter("pass");
	String lat=request.getParameter("lat");
	String lng=request.getParameter("lng");
	String hloc=request.getParameter("hloc");
	String type=request.getParameter("type");
	String imei="";
	URL url1 = new URL("https://maps.googleapis.com/maps/api/geocode/json?address="+hloc+"&sensor=true");
	URLConnection yc = url1.openConnection();
	in = new BufferedReader(new InputStreamReader(yc.getInputStream()));
	String inputLine;
	sb=new StringBuffer();
	while ((inputLine = in.readLine())!= null) {
	sb.append(" "+inputLine);

	}
	
	
	
		String data=new String(sb);
		String latitude="";
		String longitude="";

		//System.out.println(data);
		
		JSONParser parser = new JSONParser();
		Object obj=parser.parse(data);

		JSONObject jsonObject =(JSONObject)obj;
		JSONObject jsonTemp =null;
		
		//System.out.println(jsonObject);
		Set keyVal=jsonObject.keySet();
		
		if(keyVal.contains("results")){
			JSONArray msg = (JSONArray) jsonObject.get("results");
			Iterator iterator = msg.iterator();
			
			int intialValue=0;
			while (iterator.hasNext()) {
				jsonObject =(JSONObject)iterator.next();
				jsonTemp=(JSONObject)jsonObject.get("geometry");
				jsonTemp=(JSONObject)jsonTemp.get("location");
				latitude=jsonTemp.get("lat").toString();
				longitude=jsonTemp.get("lng").toString();
				
			
				
			}
			jsonObject.clear();
			jsonTemp.clear();
			keyVal.clear();
			in.close();
			
			
			}
	
	Class.forName(driver);
	con=DriverManager.getConnection(url,"root","root");
	st=con.createStatement();
	
	rs=st.executeQuery("select * from userinformation where mobilenumber='"+mobile+"'");
	if(rs.next()){
		
      out.write("\r\n");
      out.write("\t\tMobile Number already available in Server\r\n");
      out.write("\t\t");
 
	}else{
		rs=st.executeQuery("select count(*) from userinformation");
		int val=0;
		if(rs.next()){
			val=rs.getInt(1);
		}
		if(val==0){
		String query="insert into userinformation values('"+(++val)+"','"+name+"','"+dob+"','"+proj+"','"+loc+"','"+dsgn+"','"+mail+"','"+pmail+"','"+mobile+"','"+user+"','"+pass+"','"+hloc+"','"+latitude+"','"+longitude+"','"+type+"','"+imei+"')";

            System.out.println("the values are"+loc+"---"+hloc+"---"+latitude+"--"+longitude);
			int ins=st.executeUpdate(query);

			
      out.write("\r\n");
      out.write("\t\t\tRegistered Successfully\r\n");
      out.write("\t\t\t");
 
		}else{
		
			String query="insert into userinformation values('"+(++val)+"','"+name+"','"+dob+"','"+proj+"','"+loc+"','"+dsgn+"','"+mail+"','"+pmail+"','"+mobile+"','"+user+"','"+pass+"','"+hloc+"','"+latitude+"','"+longitude+"','"+type+"','"+imei+"')";
			
			 System.out.println("the values are"+loc+"---"+hloc+"---"+latitude+"--"+longitude);
			int ins=st.executeUpdate(query);

			
      out.write("\r\n");
      out.write("\t\t\tRegistered Successfully\r\n");
      out.write("\t\t\t");
 
			
		}
		
	}
	
	
	
}

      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
