/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.35
 * Generated at: 2016-04-23 06:54:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import java.util.*;

public final class selectuser_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {


    Connection con=null;
    Statement st=null;
    ResultSet rs=null;
    String driver="com.mysql.jdbc.Driver";
    String url="jdbc:mysql://localhost:3306/meetingsheduler";
    ArrayList selectdUsers=new ArrayList();
    String place="";

    
  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("    <!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<title>My Cloud Space</title>\r\n");
      out.write("<meta name=\"keywords\" content=\"free css, web template, cloudy\" />\r\n");
      out.write("<meta name=\"description\" content=\"Cloudy - free website template provided by templatemo.com\" />\r\n");
      out.write("<link href=\"templatemo_style.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/featuredcontentglider.css\" />\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"nivo-slider.css\" type=\"text/css\" media=\"screen\" />\r\n");
      out.write("\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\">\r\n");
      out.write("function clearText(field)\r\n");
      out.write("{\r\n");
      out.write("    if (field.defaultValue == field.value) field.value = '';\r\n");
      out.write("    else if (field.value == '') field.value = field.defaultValue;\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"nivo-slider.css\" type=\"text/css\" media=\"screen\" />\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" media=\"all\" href=\"jsDatePick_ltr.min.css\" />\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"jsDatePick.min.1.3.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\twindow.onload = function(){\r\n");
      out.write("\t\tnew JsDatePick({\r\n");
      out.write("\t\t\tuseMode:2,\r\n");
      out.write("\t\t\ttarget:\"date\",\r\n");
      out.write("\t\t\tdateFormat:\"%d-%M-%Y\"\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t};\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"css/featuredcontentglider.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("src=\"http://maps.googleapis.com/maps/api/js?key=AIzaSyDY0kkJiTPVd2U7aTOAwhc9ySH6oHxOIYM&sensor=false\">\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("var myCenter=new google.maps.LatLng(13.0400232,80.24002030);\r\n");
      out.write("var marker;\r\n");
      out.write("\r\n");
      out.write("function initialize()\r\n");
      out.write("{\r\n");
      out.write("var mapProp = {\r\n");
      out.write("  center:myCenter,\r\n");
      out.write("  zoom:5,\r\n");
      out.write("  mapTypeId:google.maps.MapTypeId.ROADMAP\r\n");
      out.write("  };\r\n");
      out.write("\r\n");
      out.write("var map=new google.maps.Map(document.getElementById(\"googleMap\"),mapProp);\r\n");
      out.write("\r\n");
      out.write("marker=new google.maps.Marker({\r\n");
      out.write("  position:myCenter,\r\n");
      out.write("  animation:google.maps.Animation.BOUNCE\r\n");
      out.write("  });\r\n");
      out.write("\r\n");
      out.write("marker.setMap(map);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("google.maps.event.addDomListener(window, 'load', initialize);\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function getlocation(value){\r\n");
      out.write("if(value==\"location\"){\r\n");
      out.write("\tvar xmlhttp;\r\n");
      out.write("\tif(window.XMLHttpRequest){\r\n");
      out.write("\t\txmlhttp=new XMLHttpRequest();\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\txmlhttp=new ActiveXObject(\"Microsoft.XMLHTTP\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\txmlhttp.onreadystatechange=function(){\r\n");
      out.write("\t\tif(xmlhttp.readyState==4){\r\n");
      out.write("\t\t\tdocument.getElementById(\"txtresponse\").innerHTML=xmlhttp.responseText;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\txmlhttp.open(\"POST\",\"./commonplaces.jsp\",true);\r\n");
      out.write("\t\txmlhttp.send(null);\r\n");
      out.write("}\r\n");
      out.write("}\r\n");
      out.write("function mydistance(){\r\n");
      out.write("\tdocument.getElementById(\"txt1\").innerHTML=\"\";\r\n");
      out.write("\t\r\n");
      out.write("\tvar xmlhttp;\r\n");
      out.write("\tif(window.XMLHttpRequest){\r\n");
      out.write("\t\txmlhttp=new XMLHttpRequest();\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\txmlhttp=new ActiveXObject(\"Microsoft.XMLHTTP\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\txmlhttp.onreadystatechange=function(){\r\n");
      out.write("\t\tif(xmlhttp.readyState==4){\r\n");
      out.write("\t\t\tdocument.getElementById(\"txt1\").innerHTML=xmlhttp.responseText;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\txmlhttp.open(\"POST\",\"./distance.jsp\",true);\r\n");
      out.write("\t\txmlhttp.send(null);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function mailResponse(){\r\n");
      out.write("\tvar date=document.getElementById(\"date\").value;\r\n");
      out.write("\tvar titile=document.getElementById(\"name\").value;\r\n");
      out.write("\tvar org=document.getElementById(\"organize\").value;\r\n");
      out.write("\tvar time=document.getElementById(\"time\").value;\r\n");
      out.write("\tvar venue=document.getElementById(\"txtField\").value;\r\n");
      out.write("\tif(date==\"\"||titile==\"\"|| org==\"\"||time==\"\"||venue==\"\"){\r\n");
      out.write("\t\talert(\"All The Fields Should be Filled \");\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\r\n");
      out.write("\tif(true){\r\n");
      out.write("\tvar xmlhttp;\r\n");
      out.write("\tif(window.XMLHttpRequest){\r\n");
      out.write("\t\txmlhttp=new XMLHttpRequest();\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\txmlhttp=new ActiveXObject(\"Microsoft.XMLHTTP\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\txmlhttp.onreadystatechange=function(){\r\n");
      out.write("\t\tif(xmlhttp.readyState==4){\r\n");
      out.write("\t\t\tdocument.getElementById(\"mailresponse\").innerHTML=xmlhttp.responseText;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\txmlhttp.open(\"POST\",\"./mail.jsp?date=\"+date+\"&title=\"+titile+\"&org=\"+org+\"&time=\"+time+\"&venue=\"+venue,true);\r\n");
      out.write("\t\t//xmlhttp.open(\"POST\",\"./mail.jsp\",true);\r\n");
      out.write("\t\txmlhttp.send(null);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div id=\"templatemo_wrapper_outer\">\r\n");
      out.write("<div id=\"templatemo_wrapper\">\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"temmplatmeo_header\">\r\n");
      out.write("    \r\n");
      out.write("   \t\t<div id=\"site_title\">\r\n");
      out.write("           \t<a href=\"#\">\r\n");
      out.write("            \t\r\n");
      out.write("            \t<span>My Cloud Space</span>\r\n");
      out.write("            </a>\r\n");
      out.write("        </div>\r\n");
      out.write("    \r\n");
      out.write("    \t<div id=\"templatemo_menu\">\r\n");
      out.write("        \r\n");
      out.write("            <ul>\r\n");
      out.write("                <li><a href=\"#\" class=\"current\">Home</a></li>\r\n");
      out.write("                <li><a href=\"about.html\">About Us</a></li>\r\n");
      out.write("                <li><a href=\"service.html\">Services</a></li>\r\n");
      out.write("          \t\t<li><a href=\"contact.html\">Contact </a></li>\r\n");
      out.write("            </ul>    \t\r\n");
      out.write("        \r\n");
      out.write("        </div> <!-- end of templatemo_menu -->\r\n");
      out.write("    \r\n");
      out.write("    </div> <!-- end of templatemo_header -->\r\n");
      out.write("    \r\n");
      out.write("    <div id=\"templatemo_content_wrapper_top\"></div>\r\n");
      out.write("    <div id=\"templatemo_content_wrapper\">\r\n");
      out.write("    \r\n");
      out.write("    \t\r\n");
      out.write("    \r\n");
      out.write("        <div id=\"templatemo_banner\"><span class=\"frame\"></span>\r\n");
      out.write("        \r\n");
      out.write("\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("    \r\n");
      out.write("            featuredcontentglider.init({\r\n");
      out.write("                gliderid: \"canadaprovinces\", //ID of main glider container\r\n");
      out.write("                contentclass: \"glidecontent\", //Shared CSS class name of each glider content\r\n");
      out.write("                togglerid: \"p-select\", //ID of toggler container\r\n");
      out.write("                remotecontent: \"\", //Get gliding contents from external file on server? \"filename\" or \"\" to disable\r\n");
      out.write("                selected: 0, //Default selected content index (0=1st)\r\n");
      out.write("                persiststate: false, //Remember last content shown within browser session (true/false)?\r\n");
      out.write("                speed: 500, //Glide animation duration (in milliseconds)\r\n");
      out.write("                direction: \"rightleft\", //set direction of glide: \"updown\", \"downup\", \"leftright\", or \"rightleft\"\r\n");
      out.write("                autorotate: true, //Auto rotate contents (true/false)?\r\n");
      out.write("                autorotateconfig: [3000, 2] //if auto rotate enabled, set [milliseconds_btw_rotations, cycles_before_stopping]\r\n");
      out.write("            })\r\n");
      out.write("            \r\n");
      out.write("            </script>\r\n");
      out.write("            \r\n");
      out.write("            <div id=\"canadaprovinces\" class=\"glidecontentwrapper\">\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"glidecontent\">\r\n");
      out.write("                <img src=\"images/temp3.png\" alt=\"bird\" />\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"glidecontent\">\r\n");
      out.write("            <img src=\"images/temp2.jpg\" alt=\"image\" />\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"glidecontent\">\r\n");
      out.write("            <img src=\"images/TEMP1.jpg\" alt=\"image\" />\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <div id=\"p-select\" class=\"cssbuttonstoggler\">\r\n");
      out.write("            <a href=\"#\" class=\"toc\"><span>1</span></a> <a href=\"#\" class=\"toc\"><span>2</span></a> <a href=\"#\" class=\"toc\"><span>3</span></a>\r\n");
      out.write("            \r\n");
      out.write("            </div>\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        </div> <!-- end of templatemo_banner -->\r\n");
      out.write("          ");

           if(request.getParameterValues("selection")!=null){
        	   
           String[] values=request.getParameterValues("selection");
           selectdUsers=new ArrayList();
           Class.forName(driver);
           con=DriverManager.getConnection(url,"root","root");
           st=con.createStatement();
           try{
        	   for(int i=0;i<values.length;i++){
            	   rs=st.executeQuery("select * from userinformation where userid='"+values[i]+"'");
            	   while(rs.next()){
            		   selectdUsers.add(rs.getString(2));
            		   selectdUsers.add(rs.getString(13));
            		   selectdUsers.add(rs.getString(14));
            		   selectdUsers.add(rs.getString(15));
            		   selectdUsers.add(rs.getString(9));
            		   
            	   }}
           int delete=st.executeUpdate("delete from selectedusers");
           }catch(Exception ex){
        	   ex.printStackTrace();
           }finally{
        	   con.close();
        	   st.close();
        	   rs.close();
           }}else{
			   selectdUsers=new ArrayList();
		   }
           
      out.write("\r\n");
      out.write("        \r\n");
      out.write("    \t    \r\n");
      out.write("    \r\n");
      out.write("    \t<div id=\"content\">\r\n");
      out.write("        \r\n");
      out.write("        \t<div class=\"full_width\" style=\"background-color:#C2D6FF; border:2px solid #6699FF;height:600px;\">\r\n");
      out.write("        \t\r\n");
      out.write("        \t<div id=\"cccc\">\r\n");
      out.write("        \t<div class=\"content-attribute\">\r\n");
      out.write("        \t&nbsp;&nbsp;&nbsp;<p><table border=\"1\" cellpadding=\"8\" cellspacing=\"8\" style=\"height: 100px;\">\r\n");
      out.write("        \t<th bgcolor=\"\" colspan=\"5\"><font size=\"5\" color=\"red\"><center>Staff Information</center></font></th>\r\n");
      out.write("        \t<tr><td><b>Staff Name</b></td><td><b>Latitude</b></td><td><b>Longitude</b></td><td><b>Vehicle</b></td><td><b>Mobile Number</b></td></tr>\r\n");
      out.write("        \t");

        	for(int val=0;val<selectdUsers.size();val=val+5){
        		try{	
        		
      out.write("\r\n");
      out.write("        \t\t<tr>\r\n");
      out.write("        \t\t<td>");
      out.print(selectdUsers.get(val).toString() );
      out.write("</td>\r\n");
      out.write("        \t\t<td>");
      out.print(selectdUsers.get(val+1).toString() );
      out.write("</td>\r\n");
      out.write("        \t\t<td>");
      out.print(selectdUsers.get(val+2).toString() );
      out.write("</td>\r\n");
      out.write("           \t\t<td>");
      out.print(selectdUsers.get(val+3).toString() );
      out.write("</td>\r\n");
      out.write("          \t\t<td>");
      out.print(selectdUsers.get(val+4).toString() );
      out.write("</td>\r\n");
      out.write("           \t\t</tr>\r\n");
      out.write("        \t\t");
 
        		 Class.forName(driver);
                con=DriverManager.getConnection(url,"root","root");
                st=con.createStatement();
                int insert=st.executeUpdate("insert into selectedusers values('"+selectdUsers.get(val).toString()+"','"+selectdUsers.get(val+1).toString()+"','"+selectdUsers.get(val+2).toString()+"','"+selectdUsers.get(val+3).toString()+"','"+selectdUsers.get(val+4).toString()+"')");
                }catch(Exception ex){
        		ex.printStackTrace();
        	}finally{
        		con.close();
        		st.close();
        	}}
        	
      out.write("\r\n");
      out.write("\r\n");
      out.write("        \t\t</table>\r\n");
      out.write("        \t\r\n");
      out.write("        \t</div>\r\n");
      out.write("        \t\r\n");
      out.write("        \t\r\n");
      out.write("        \t<br>\r\n");
      out.write("        \t<input type=\"submit\" value=\"common places\" style=\"margin-left:40px;border: 2;background-color: maroon;font-family: serif;color: white;\" onclick=\"getlocation('location');\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href=\"logout1.jsp\" style=\"font-style: normal;color:maroon;\">Logout</a>\r\n");
      out.write("        \t<br></br>\r\n");
      out.write("        \t<div id=\"txtresponse\">\r\n");
      out.write("        \t<textarea rows=\"10\" cols=\"30\" style=\"margin-left:20px;\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</textarea>\r\n");
      out.write("        \t</div>\r\n");
      out.write("        \t</div>\r\n");
      out.write("        \t\r\n");
      out.write("        \t<div id=\"cc\">\r\n");
      out.write("      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span id=\"mailresponse\" style=\"font-family:serif;color: maroon;\"></span>\r\n");
      out.write("        \t\r\n");
      out.write("        \t<div id=\"content-attribute2\" >\r\n");
      out.write("        \t\tMeeting Date &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type=\"text\" id=\"date\" style=\"margin:10px 0 2px 20px;\"><br>\r\n");
      out.write("        \t\tMeeting Title <input type=\"text\" id=\"name\" style=\"margin:10px 0 2px 20px;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href=\"index.html\" style=\"border: thick;color: maroon;\">Click to Home Page</a><br>\r\n");
      out.write("        \t\tOrganizer <input type=\"text\" id=\"organize\" style=\"margin:10px 0 2px 40px;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href=\"meeting.jsp\" style=\"border: thick;color: maroon;\">Click to Meeting Page</a><br>\r\n");
      out.write("        \t\tTime<input type=\"text\" id=\"time\" style=\"margin:10px 0 2px 70px;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href=\"process.jsp\" style=\"border: thick;color: maroon;\">Click to Admin Page</a><br>\r\n");
      out.write("        \t\t<div id=\"txt1\">Get venue <input type=\"text\" name=\"txtField\" id=\"txtField\" style=\"margin:10px 0 2px 35px;\"></div>\r\n");
      out.write("        \t\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type=\"submit\" value=\"get venue\" style=\"margin:10px 0 2px 35px; border: 2;background-color: maroon;font-family: serif;color: white;\" onclick=\"mydistance();\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href=\"distanceshow.jsp\" style=\"border: thick;color: maroon;\">Show Distance</a><br>\r\n");
      out.write("        \t\t\r\n");
      out.write("        \t\t   <input type=\"submit\"  value=\"Send Mail\" style=\"margin:0 0 0 120px;border: 2;background-color: maroon;font-family: serif;color: white;\" onclick=\"return mailResponse();\">\r\n");
      out.write("        \t\r\n");
      out.write("        \t\t\r\n");
      out.write("        \t\t\r\n");
      out.write("        \t\r\n");
      out.write("        \t</div>\r\n");
      out.write("        \t\r\n");
      out.write("    \t<div id=\"content-attribute3\">\r\n");
      out.write("    \t<div id=\"googleMap\" style=\"width:280px;height:230px; border:2px solid #000;\"></div>\r\n");
      out.write("    \t\r\n");
      out.write("    \t</div>    \t\r\n");
      out.write("        \t\r\n");
      out.write("        \t</div>\r\n");
      out.write("        \t\r\n");
      out.write("        \t\r\n");
      out.write("            <center>\r\n");
      out.write("           \r\n");
      out.write("          \r\n");
      out.write("           </center>\r\n");
      out.write("        \r\n");
      out.write("\t\t</div> <!-- end of content -->\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</div><div id=\"templatemo_content_wrapper_bottom\"></div> <!-- end of templatemo_wrapper -->\r\n");
      out.write("\r\n");
      out.write("        <div id=\"templatemo_footer\">\r\n");
      out.write("   \t     </div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
